name: interview_junior_flutter
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  bloc: ^8.1.4
  bloc_concurrency: ^0.2.5
  bloc_test: ^9.1.7
  flutter_bloc: ^8.1.5
  hydrated_bloc: ^9.1.5
  json_annotation: ^4.8.1
  path_provider: ^2.0.8
  injectable: ^2.4.1
  get_it: ^7.7.0
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.17
  cached_network_image: ^3.4.1
  equatable: ^2.0.7
  flutter_screenutil: ^5.9.0
  shared_preferences: ^2.2.2
  intl: ^0.19.0
  sqflite: ^2.4.2
  animated_bottom_navigation_bar: ^1.4.0
  auto_size_text: ^3.0.0
  path: ^1.9.1
  table_calendar: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  launcher_name: ^1.0.2
  flutter_launcher_icons: ^0.13.1
  # dart run build_runner build
  json_serializable: ^6.8.0
  build_runner: ^2.4.9
  # dart run build_runner build --delete-conflicting-outputs
  injectable_generator: ^2.6.1

# dart run launcher_name:main
launcher_name:
  default: "Test Flutter Junior"

# flutter pub run flutter_launcher_icons
flutter_launcher_icons:
  android: true
  ios: true
  adaptive_icon_background: "assets/images/img_logo_company.jfif"

flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/img_logo_company.jfif"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/images/
    - assets/icons/
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter/Inter_18pt-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter/Inter_18pt-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter/Inter_18pt-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter/Inter_18pt-Bold.ttf
          weight: 700


